services:

  dnsmasq:
    image: zone9cloud/dnsmasq:0.1.1
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./config/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - ./logs:/var/log/dnsmasq      
    restart: always
    networks:
      dnsmasq:
        ipv4_address: 10.0.0.50
    
  ns53:
    image: zone9cloud/dynamicdns:0.1.1 
    hostname: ns1.ns53.me
    environment:
      - DEBUG=1
      - DNS_DOMAIN=ns53.me
      - DNS_NAMESERVERS="ns1.ns53.me=127.0.0.1 ns1.ns53.me=127.0.0.1"
      - DNS_SOA_NS=ns1.ns53.me
      - DNS_SOA_HOSTMASTER=hostmaster@ns53.me
    restart: always
    networks:
      dnsmasq:
        ipv4_address: 10.0.0.53

  ns10:
    image: zone9cloud/dynamicdns:0.1.1 
    hostname: ns1.ns10.me
    environment:
      - DEBUG=1
      - DNS_DOMAIN=ns10.me
      - DNS_NAMESERVERS="ns1.ns10.me=127.0.0.1 ns1.ns10.me=127.0.0.1"
      - DNS_SOA_NS=ns1.ns10.me
      - DNS_SOA_HOSTMASTER=hostmaster@ns10.me
    restart: always
    networks:
      dnsmasq:
        ipv4_address: 10.0.0.10
                
  ns172:
    image: zone9cloud/dynamicdns:0.1.1 
    hostname: ns1.ns172.me
    environment:
      - DEBUG=1
      - DNS_DOMAIN=ns172.me
      - DNS_NAMESERVERS="ns1.ns172.me=127.0.0.1 ns1.ns172.me=127.0.0.1"
      - DNS_SOA_NS=ns1.ns172.me
      - DNS_SOA_HOSTMASTER=hostmaster@ns172.me  
    restart: always
    networks:
      dnsmasq:
        ipv4_address: 10.0.0.172

  ns192:
    image: zone9cloud/dynamicdns:0.1.1 
    hostname: ns1.ns192.me
    environment:
      - DEBUG=1
      - DNS_DOMAIN=ns192.me
      - DNS_NAMESERVERS="ns1.ns192.me=127.0.0.1 ns1.ns192.me=127.0.0.1"
      - DNS_SOA_NS=ns1.ns192.me
      - DNS_SOA_HOSTMASTER=hostmaster@ns192.me
    restart: always
    networks:
      dnsmasq:
        ipv4_address: 10.0.0.192


networks:
  dnsmasq:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/24
         gateway: 10.0.0.1